### ISSUE TITLE
Double function connect Database

### ISSUE THREAD

**Issue by rinonmac** [GreenRunchly/icms#1]
Terdapat double function connect database di 2 file tersebut:
icms-load.php:
```
/// Load DB Config
	if ( file_exists( app_theme_dir() . '/core/db.php' ) ) {
		include app_theme_dir() . '/core/db.php';
		/// Connect to Main db used in ICMS
		if ( ! defined( 'ICMS_DB_NAME' ) ){
			$icms_db_conn = app_db_connect();
		}
	}else{
		define('ICMS_DB_NAME', ''); /// Masukan nama database as default
	    define('ICMS_DB_USER', ''); /// User database as default
	    define('ICMS_DB_USER_PASS', ''); /// User password akun database as default
	    define('ICMS_DB_HOST', ''); /// Server db as default
	}
```

db.php
```
    /// NOTE: Config for each app
    define('ICMS_DB_NAME', ''); /// Masukan nama database as default
    define('ICMS_DB_USER', ''); /// User database as default
    define('ICMS_DB_USER_PASS', ''); /// User password akun database as default
    define('ICMS_DB_HOST', ''); /// Server db as default
```

Di readme tertulis jika connect database menggunakan function connect db file db.php , lalu mengapa ada fungsi connect db di file icms-load.php ? 

Saran: di function connect db di icms-load.php diganti ke else show error message jika db tersebut tidak ada

**Comment by GreenRunchly** [comment]
Hanya abaikan saja db constant pada file icms-load.php, sesuai yang tertulis pada readme file, sudah di beri peringatan juga disana, itu akan dipilih otomatis jika file db.php pada core theme folder menghilang, sehingga menjadi default configuration.
