### ISSUE TITLE
Simpan creditentials di database

### ISSUE THREAD

**Issue by rinonmac** [GreenRunchly/icms#2]
Apakah bisa diganti penyimpanan creditentials database ke .env ? Ada kemungkinan file .php bisa bocor

**Comment by GreenRunchly** [comment]
Dimaksudkan untuk memudahkan user dalam berpindah-pindah file layaknya wordpress, bedanya db config berada didalam file masing folder tema, dan user dapat mengubah permission folder tersebut agar tidak dilihat/dimodifikasi dengan injeksi ataupun lewat internal, agar lebih tenang bisa menggunakan ioncube encoder atau sejenisnya sehingga file asli akan tetap di tangan user/komputer lokal
